# Generated by Django 5.2.7 on 2026-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('suite', 'Suite'), ('standard', 'Standard Room'), ('deluxe', 'Deluxe Room')], max_length=100)),
                ('pricePerNIght', models.IntegerField(default=150)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('USD', 'EUR'), ('UGX', 'UGX')], default='UGX', max_length=10)),
                ('maxOccupancy', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1)),
            ],
        ),
    ]
